---
title: "qPCR analysis"
author: "Melissa Naugle"
date: "3/22/2021"
output: html_document
---

```{r setup, include=FALSE}
setwd(dir = "~/Desktop/GitHub/Symbiont_qPCR/")
rm( list = ls())
graphics.off()
library(ggplot2)
library(ggpubr)
library(plyr)
library(dplyr)
library(tidyr)
library(reshape2)
library(mosaic)
library(RColorBrewer)

```


```{r readdata}
#read in all clean csv files
dat <- read.csv("cleandata/2014data/2014data_clean_04_26_21_ahyac31-36,38-43_50th.csv")

#bind data files together
#dat <- rbind(dat1,dat2)
#nrow(dat)

head(dat)
dat$FAM <- as.numeric(dat$FAM)
dat$VIC <- as.numeric(dat$VIC)
dat <- dat[!(dat$Sample=="neg con"),]


dat$Site = "n"
#31-39 tele
#40-49 cannery, but not totally sure about 40!!

#Manually choose sites to fill in based on data sheet 
#can change rows below 

#until row 24 = tele
#rows 25-36 are cannery

dat[1:24,4] <- "Faga'tele"
dat[25:36,4] <- "Cannery"

#add month sampled

dat$samplemonth = "n"
dat[1:36,5] <- "March"

```





```{r logfirst}
#try log transforming ct values first, then calc after

dat_log <- dat
dat_log$FAM_log <- log10(dat_log$FAM)
dat_log$VIC_log <- log10(dat_log$VIC)


dat_ratio_log <- dat_log %>%
  group_by(Sample, Site) %>%
  summarize(FAM_log_mean = mean(FAM_log, na.rm = TRUE), VIC_log_mean = mean(VIC_log, na.rm = TRUE))
dat_ratio_log


dat_ratio_log$cellnum_C <- (2^(40 - dat_ratio_log$VIC_log_mean)) / 9
dat_ratio_log$cellnum_C[is.na(dat_ratio_log$VIC_log_mean)] <- (2^(40-10000000000000))
dat_ratio_log$cellnum_D <- (2^(40 - dat_ratio_log$FAM_log_mean)) / 1


dat_ratio_log$D_prop <- dat_ratio_log$cellnum_D / (dat_ratio_log$cellnum_C + dat_ratio_log$cellnum_D)
dat_ratio_log$C_prop <- dat_ratio_log$cellnum_C / (dat_ratio_log$cellnum_C + dat_ratio_log$cellnum_D)

dat_ratio_gather <- gather(dat_ratio_log, "Species", "Ratio", 7:8)
dat_ratio_gather$Ratio <- round(dat_ratio_gather$Ratio, digits = 4)

ggplot(dat_ratio_log, aes(x = Site, y = C_prop, fill = Site)) + geom_violin() + theme_bw()  + 
  scale_fill_brewer(palette = "Set3") + ylab("Log Proportion of Cladocopium") + xlab("") + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.1, binwidth = 0.04)

#ggsave("figures/2014_figs_date.pdf", width = 6, height = 4)

#write.csv(dat_ratio_log, "/Users/Melissa/Desktop/GitHub/Symbiont_qPCR/cleandata/symbiont_log_ratios.csv", row.names = F)

dat_ratio_means <- dat_ratio_log %>%
  group_by(Site) %>%
  summarize(D_prop_avg = mean(D_prop), C_prop_avg = mean(C_prop))

dat_ratio_means <- gather(dat_ratio_means, "Species", "Ratio", 2:3)
dat_ratio_means$logRatio <- dat_ratio_means$Ratio


#plots mean proportions for each site
ggplot(dat_ratio_means, aes(x = Site, y = logRatio, fill = Species)) + geom_col() + theme_bw()  + ylab("Log Proportion of Durisdinium and Cladocopium") + scale_fill_manual(labels = c("Cladocopium", "Durisdinium"), values = c("violetred2", "royalblue3")) + xlab("") + theme(legend.title = element_blank())

#ggsave("figures/symbionts_logratio_03_25_21.pdf", width = 6, height = 4)


```
C+D corals: 
Tele 1-6
Vatia 5-6
Alu 2

```{r stats}

#no assumptions met 

dat_ratio_log$CDratio_log <- dat_ratio_log$cellnum_C/dat_ratio_log$cellnum_D

shapiro.test(dat_ratio_log$CDratio_log)
#not normal
#p = 1.2e-09

shapiro.test(dat_ratio_log$cellnum_D)
shapiro.test(dat_ratio_log$C_prop)
shapiro.test(dat_ratio_log$D_prop)

bartlett.test(CDratio_log ~ Site, data=dat_ratio_log)
#not equal
#p < 2.2e-16

modelCD = lm(CDratio_log ~ Site, data=dat_ratio_log) 
anova(modelCD) 
#very signif 
shapiro.test(modelCD$residuals)
#not normal
TukeyHSD(modelCD,"Site")


```

