---
title: "Symbiont_phys_correlation"
author: "Melissa Naugle"
date: "4/19/2021"
output: html_document
---


```{r readdata}
setwd(dir = "~/Desktop/GitHub/Symbiont_qPCR/")
rm( list = ls())
graphics.off()
library(ggplot2)
library(ggpubr)
require(plyr)
library(dplyr)
library(corrplot)
```


```{r }
pam <- read.csv("/Users/Melissa/Desktop/GitHub/CBASS_bleachingdata/raw data sheets/PAM_data_normalized.csv")
pam$SiteColony <- paste(pam$Site, pam$Colony)
pam$t35_normalizedto28_pam <- pam$t35_normalizedto28
pam <- select(pam, "SiteColony", "t35_normalizedto28_pam")
pam <- pam %>% 
  group_by(SiteColony) %>%
  summarise(mean_t35_normalizedto28_pam = mean(t35_normalizedto28_pam)) 

avgred <- read.csv("/Users/Melissa/Desktop/GitHub/CBASS_bleachingdata/raw data sheets/AverageRedData_normalized.csv")
avgred$SiteColony <- paste(avgred$Site, avgred$Colony)
avgred$t35_normalizedto28_avgred <- avgred$t35_normalizedto28
avgred <- select(avgred, "SiteColony", "t35_normalizedto28_avgred")
avgred <- avgred %>% 
  group_by(SiteColony) %>%
  summarise(mean_t35_normalizedto28_avgred = mean(t35_normalizedto28_avgred)) 

symbionts <- read.csv("/Users/Melissa/Desktop/GitHub/Symbiont_qPCR/cleandata/symbiont_log_ratios_07_17_21.csv")
#add colony number to symbiont sheet
Colony <- data.frame(do.call('rbind', strsplit(as.character(symbionts$Sample), "F", fixed = T)))
symbionts$Colony <- Colony$X2
symbionts$SiteColony <- paste(symbionts$Site, symbionts$Colony)
symbionts <- select(symbionts, "SiteColony", "D_prop", "C_prop", "cellnum_D", "cellnum_C", "CDratio_log")

data <- merge(pam, avgred, all = T)
data <- merge(data, symbionts, all = T)
```

```{r analysis}
p1 = ggplot(data, aes(x=C_prop)) + geom_line(aes(y=mean_t35_normalizedto28_pam), color="blue") + xlab("Log Proportion of Cladocopium") + ylab("Mean PAM Fv/Fm") + theme_bw()  + ylim(-0.06,0.05) + geom_point(data=data,aes(x=C_prop,y=mean_t35_normalizedto28_pam))
p2 = ggplot(data, aes(x=C_prop)) + geom_line(aes(y=mean_t35_normalizedto28_avgred), color="red") + xlab("Log Proportion of Cladocopium") + ylab("Mean Average Red Intensity") + theme_bw()  + geom_point(data=data,aes(x=C_prop,y=mean_t35_normalizedto28_avgred))
p3 = ggplot(data, aes(x=C_prop)) + geom_line(aes(y=mean_t35_normalizedto28_pam), color="blue") + xlab("Log Proportion of Cladocopium") + ylab("Mean PAM Fv/Fm") + theme_bw() + xlim(0, 0.003) + ylim(-0.06,0.05) + geom_point(data=data,aes(x=C_prop,y=mean_t35_normalizedto28_pam))
p4 = ggplot(data, aes(x=C_prop)) + geom_line(aes(y=mean_t35_normalizedto28_avgred), color="red") + xlab("Log Proportion of Cladocopium") + ylab("Mean Average Red Intensity") + theme_bw()  + xlim(0, 0.003) + geom_point(data=data,aes(x=C_prop,y=mean_t35_normalizedto28_avgred))

ggarrange(p1,p2,p3,p4)

cor.test(data$C_prop, data$mean_t35_normalizedto28_avgred, method = "spearman")
cor.test(data$C_prop, data$mean_t35_normalizedto28_pam, method = "spearman")

#ggsave("/Users/Melissa/Desktop/GitHub/Symbiont_qPCR/figures/symbiontCprop_bleaching_07_17_21.pdf", width = 6, height = 4)

```


#Two-variable metric plotted against symbiont community to look for correlation 
try prop C and C:D ratio

```{r}
twovar_thermotol <- read.csv("../CBASS_bleachingdata/CRCP_2014/UniqueColony_SCLERAModeling_2019_v1.5.csv")

symbionts <- read.csv("/Users/Melissa/Desktop/GitHub/Symbiont_qPCR/cleandata/symbiont_log_ratios_07_17_21.csv")
#add colony number to symbiont sheet
Colony <- data.frame(do.call('rbind', strsplit(as.character(symbionts$Sample), "F", fixed = T)))
symbionts$Colony <- Colony$X2
symbionts$Site_Col <- paste0(symbionts$Site,"_", symbionts$Colony)
symbionts <- select(symbionts, "Site_Col", "D_prop", "C_prop", "cellnum_D", "cellnum_C", "CDratio_log")

data_sym_tt <- merge(twovar_thermotol, symbionts, all = T)

ggplot(data_sym_tt, aes(x=C_prop, y = Phenotype.X0.mn, col = Site)) + geom_point() + xlab("Log Proportion of Cladocopium") + ylab("Two Variable Thermotolerance \n higher = more thermotol") + theme_bw() + xlim(0, 0.045) + ggtitle("Log prop C by thermotolerance \n missing one outlier with high C prop")

#looks better
ggplot(data_sym_tt, aes(x= CDratio_log, y = Phenotype.X0.mn, col = Site)) + geom_point(size = 5) + xlab("Log C:D Ratio \n left = more D, right = more C") + ylab("Two Variable Thermotolerance \n higher = more thermotol") + theme_bw() + ggtitle("Log C:D ratio by two-metric thermotolerance")

ggsave("figures/LogCDratio_twometricthermotolerance_2019_08_04_2021.jpg")

#CWC
ggplot(data_sym_tt, aes(x= CDratio_log, y = CWC3.X0, col = Site)) + geom_point(size = 5) + xlab("Log C:D Ratio \n left = more D, right = more C") + ylab("Color Watch Card \n higher = more thermotol") + theme_bw() + ggtitle("Log C:D ratio by Color Watch Card")


ggsave("figures/LogCDratio_cwc_2019_08_04_2021.jpg")

#red intensity
ggplot(data_sym_tt, aes(x= CDratio_log, y = ARed.X0, col = Site)) + geom_point(size = 5) + xlab("Log C:D Ratio \n left = more D, right = more C") + ylab("Red Intensity \n higher = more thermotol") + theme_bw() + ggtitle("Log C:D ratio by Red Intensity")

ggsave("figures/LogCDratio_redintensity_2019_08_04_2021.jpg")
```



















